version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_concessionaria
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: concessionaria_db
    ports:
      - "5432:5432"